namespace: ingress-nginx

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/ports/-
      value:
        name: prometheus
        containerPort: 9113
    - op: add
      path: /spec/template/metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/scheme: http
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-metrics
  target:
    kind: Deployment
    name: ingress-nginx-controller

resources:
  - manifests/ingress-nginx.yaml
